name: publish-to-git

on: [push, pull_request]

jobs:
  test-setup-vsdevenv:
    name: test
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ 'windows-latest', 'ubuntu-latest' ]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - run: |
          cd setup-vsdevenv
          npm install
      - run: node setup-vsdevenv/index.js
      - run: cl.exe /version