name: setup-ninja

on: [pull_request]

jobs:
  test-setup-ninja:
    name: test setup-ninja
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]

    steps:
      - uses: actions/checkout@master
      - uses: ./setup-ninja
      - run: ninja --version